### PR TITLE
Support partially filled containers 

### PR DESCRIPTION
**Pull request by Josharias**
Thanks to xrtariq2594 for the initiative of partially filled containers.

Also in this PR, consuming the event after filling the container so only one action happens per ActivateRequest.

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Good work! When you feel it's good enough, let me know and I'll merge.

Should we look into #10 and see if we can add an empty container action?

**Comment by Josharias** [comment]
Yeah,  I do not have any brilliant ideas for #10.  I am not convinced adding yet another keybinding for emptying a bucket is the right move,  Keeping left click for attack and right click for use item seems a noble cause to attain to, if we can.  But that doesnt really allow this alternate action thing.  In MC,  using shift-click often did something special,  but then many used it to do a reverse action with inventory interaction...

This PR is good to go.

**Comment by Cervator** [comment]
For emptying here's an attempt at a simple system since I'd also like to avoid more keybinds:

While holding a container
- Left click still attacks to break whatever selected block/object
- Right click attempts to pair the container with the target as _either_ a consumer or a provider

That can then leave up the exact action to the block, with a sane default or two in place.
- Provider: If the target block is water then right click fills the container, if possible
- Consumer: If the target block is a sifting station (IIRC it can be filled that way?) then you empty as much liquid as possible into the station
- Provider: If the target block is a tank then fill the container if the container isn't full. If the container _is_ full then try to fill the tank instead. Probably do nothing if the liquids are not the same (allow some more advanced functionality somewhere to worry about "liquid alloys", heh)
- Provider: If the target block is _any_ liquid then attempt to fill the container. Or if the container is full then dump instead.
- Consumer: If the target block is anything else (like a dirt block, a tree trunk, a flower) then dump the container's content and offer it up to the block if it cares (fancy gardening system could require hand-watering of plants)

Possibly could connect that to a module like the "Hydration" bit mentioned in #20 adding the logic there for hydrating things and providing liquids. Or Fluids. I dunno. Maybe Hydration is the minimal "I want to get water from this water block to my belly" and Fluids is for more advanced storage. Or Hydration just does direct-drinking from a source ..

Probably this PR isn't the ideal place to leave this design, but I'm waaay behind on notifications and just noticed this one by chance, please move this to anywhere more appropriate like #10 if desired :-)

**Comment by Josharias** [comment]
I think we basically have everything except for interacting with the world when the bucket is filled.

I didnt realize emptying a bucket could be so tricky.  Still not completely sold on the best way to empty back into the world (specially since I havent tried making blocks of extra liquids yet).  Possibly Ill put in something special to ManualLabor to craft a full bucket into an empty one.  That way you are not stuck if you fill it.

**Comment by Cervator** [comment]
Using crafting to empty a bucket sounds really awkward :-)

Rather than fully implement a consumer/provider system right away, maybe just any mouse right click while holding a bucket and NOT facing a target like water, a tank, or a workstation would empty it?

**Comment by Josharias** [comment]
The misclicks would be annoying.  "Arg,  I just lost my bucket contents... again"  Because I am totally that kind of player that misclicks all the time. :)

**Comment by Cervator** [comment]
Haha, true - _but_ that's part of the experience, especially when you have lava buckets! ;-)

(admittedly that would take also creating a new liquid block rather than just dumping...)

In short: change the toolbar slot and the problem disappears :-)

**Comment by Josharias** [comment]
I ended up making Thirst because of time constraints.  Feel free to do the rename.

**Pull request merged**
